sudo: required
service:
  - docker

before_install:
  - docker build -t dkubiak789/docker-react -f Dockerfile.dev .

script:
  - docker run dkubiak789/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-2-632589165592
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
